### ISSUE TITLE
Generate/Iterate vulnerable private keys

### ISSUE THREAD

**Issue by khcnz** [crocs-muni/roca#13]
With the information currently available is it possible to GENERATE vulnerable private keys (other than bruteforce), and if so what sort of keyspace is vulnerable?

I have a use case where I would like to search for vulnerable keys from a hash of the private key. Would obviously need to generate keys to be able to test this but not currently sure of the feasibility of this.

**Comment by ph4r05** [comment]
This will be available after full disclosure on CCS 2017 conference. Mathematical details are not public till that point.
