### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by nealmcb** [crocs-muni/roca#25]
The current code works with Python 2.7.13. Not with 2.7.6, or with Python 3.
With Python 3, users get errors like 

* `TypeError: startswith first arg must be bytes or a tuple of bytes, not str` (#23)

The README.md shows how to use Docker, or pyenv to get 2.7.13 (or any other Python version).

Porting to Python 3 would make it easier to run in many environments.  Great tips and tools are available:

* [Porting Python 2 Code to Python 3 — Python 3.6.3 documentation](https://docs.python.org/3/howto/pyporting.html)

**Comment by ph4r05** [comment]
v1.2.0 supports py3
