### ISSUE TITLE
revert

### ISSUE THREAD

**Issue by scholtz** [crocs-muni/roca#28]
@ph4r05 Why did you revert? https://github.com/crocs-muni/roca/commit/3f042a3d01748c3ab9b4c0a305ffe7ce2589a455 ?

**Comment by ph4r05** [comment]
due to reasons in #27 

It will be better to create a standalone repository for C# checker with advanced format support.

Edit: I am happy to link it from readme.

**Comment by scholtz** [comment]
i see.. i am using vs 2017, so i did not want to change whole project (as it seems to be VS2015 version), and thats why i added the dependencies only to the comments when doing PR..

still i think that my code change is useful, so feel free to merge it back someone..

**Comment by ph4r05** [comment]
Hi there!

If you are interested you can create a standalone repository under your account and push the code there. Then pls create PR with readme update linking your repository from our readme. 

Thanks a lot for your contirbution!
