### ISSUE TITLE
Add support for URLs

### ISSUE THREAD

**Issue by ptman** [crocs-muni/roca#3]
Seems it would be useful to allow giving URLs on the command line for testing. Or am I totally misunderstanding something?

**Comment by ph4r05** [comment]
We left out URL because the number of positive keys in this domain was very small (small units in millions).

We may consider adding URL later, or if PR comes we are happy to merge :)

**Comment by pirxthepilot** [comment]
Somewhat related: #29 - would be great if someone can review?

**Comment by ph4r05** [comment]
improved by #36 , closing
