### ISSUE TITLE
Rozklad N

### ISSUE THREAD

**Issue by scholtz** [crocs-muni/roca#38]
Čaute, snažíme sa rozložiť konkrétne číslo na 2 prvočísla..  na základe tohto threadu https://platforma.slovensko.digital/t/eid-prelomene/4291/378 tu: https://platforma.slovensko.digital/t/hackovanie-suchalovho-kluca/4348

Nechcete pomôcť?

Ináč som si všimol, že v .net teste sa vracia true iba v prípade ak celá iterácia roca testu nič nenájde. Nechápem prečo, lebo ak si vymyslím vlastnú iteráciu, npr či N % 2 = 0 a nenájde mi to žiadny výsledok, automaticky to hádam neznamená, že certifikát je chybný ? Správne by malo byť, že ak sa identifikuje nejaké číslo napríklad N % 3 = 1, tak práve vtedy test detekuje chybný certifikát.

**Comment by petrs** [comment]
Dear Scholtz,
we are sorry, but the tools this repository are intended only for the detection of vulnerable keys, nothing else. Hope you understand.

**Comment by scholtz** [comment]
I understand, but for you conference, you could be prepared that not only you found private key on your chosen 2k bit keys, but also a real one..

**Comment by scholtz** [comment]
also you have not commented the potential bug in your c# project..

**Comment by petrs** [comment]
We do not plan to factorize public keys neither for Slovakia, nor for other country. Please focus only on discussion about the detection tools here.
In case you see any problem with C# code, please fork the repo and correct it.
