### ISSUE TITLE
false positives on safe key lengths

### ISSUE THREAD

**Issue by mimaen** [crocs-muni/roca#49]
Online checker marks keys with a length of 1920 bits as vulnerables. But this key size is safe to Coppersmith's attack (figure 1 on paper).

Is the detection tool aware of the lengths considered safe?

**Comment by ph4r05** [comment]
Thanks for the feedback!

The keys still do contain the structure which makes them weaker compared to the properly generated RSA keys. 

Online detection tool makes only a difference for 3k keys due to their usage in eIDs. Other lengths are not treated differently.
