### ISSUE TITLE
would like positive X.509 certificate test vector

### ISSUE THREAD

**Issue by iay** [crocs-muni/roca#6]
I'm trying to embed the Java code into another testing tool that is aimed at X.509 certificates, and I'm therefore looking for an X.509 test vector.

At the moment it looks like the certificate-format test files (`cert01.pem`, `cert02.pem`, `cert03.pem`) are all negative tests. Similarly `privkey03.pem`.

It would be useful to have an X.509 version of one of the other positive tests, or a private key file that I could use with `openssl` to create one myself.

**Comment by ph4r05** [comment]
Another types of positive test keys would be great!
Is it enough for you p, q, N to create such files?

I can get back to it in few hours.

Thanks!

**Comment by iay** [comment]
I think so, using something like <https://github.com/ius/rsatool>. If you can give me the components I will look at it in the morning.

**Comment by ph4r05** [comment]
thanks, based on this I've added cert04.pem, cert05.pem which are positive

**Comment by iay** [comment]
Many thanks, those are just what I needed.
