### ISSUE TITLE
Vulnerable key output

### ISSUE THREAD

**Issue by jan-swiecki** [crocs-muni/roca#7]
Can you post example output of roca-detect for vulnerable keys? It is not clear to how to interpret console output.

**Comment by alexloney** [comment]
Under roca/tests/data/ there are test files, it looks like the files cert04.pem and cert05.pem both contain vulnerable keys. Here's what the tool prints when checking the files:

> $ roca-detect cert04.pem
> 2017-10-16 17:09:38 [32331] WARNING Fingerprint found in the Certificate cert04.pem idx 0
> {"type": "pem-cert", "fname": "cert04.pem", "idx": 0, "fprint": "f49266bd45ac6a55cfb36b032d7c3c9725f557c053054f4a91523b4a45277b58", "subject": "CN: localhost", "issuer": "CN: localhost", "issuer_org": null, "created_at": "2017-10-16", "created_at_utc": 1508182701.0, "not_valid_after_utc": 1539718701.0, "pem": "-----BEGIN CERTIFICATE-----\nMIICpTCCAYwCCQC2u0PIfFaGMjANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAls\nb2NhbGhvc3QwHhcNMTcxMDE2MTkzODIxWhcNMTgxMDE2MTkzODIxWjAUMRIwEAYD\nVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQJZ\nJ7UrpeaMjJJou5IY83ZzYUymVBj0dFsUPNTuU/lJHJoOHC8jqVFjBq/784ZnuHG8\nDMguYPW7Gp+hWlZxp2XJ8huVh9gBFZZDcqODyIOw3L9sd1cGsx6v8+P9SIVZoIze\nog+al8TFm2uKjuykV9SoINSVCfdZM2MCvKGjaQsICRgR+Fjy6M6lpiNVrW4EHRk1\n7aWSibWXaDtz4mV650v/x2Dk1RPMh9uTVZGOqgjTmLvl9oNdyHElIRubNrOgvHC5\nk6bLP30stAYd5z25cslCrfmVW2/kzZDwDQiK7ASvH17/kfIa9e1EYXx9uAk/lTZt\nsmWAxK85neuU+bFBMFvhAgMBAAEwDQYJKoZIhvcNAQELBQADggECAAG7W49CYRUk\nYAFRGXu3M85MKOISyc/kkJ8nbHdV6GxJ05FkoDKbcbZ7nncJiIp2VMAMEIP4bRTJ\n5U4g4vSZlmCs8BDmV3Ts/tbDCM6eqK+2hwjhUnCnmmsLt4xVUeAAsWUHl9AVtjzd\noYlm1Kk20QBzNpsvM/gFS5B+duHvTSfELfoq9Pdfvmn2gEXJHe9scO8bfT3fm15z\nR6AUYsSsxAhup2Rix6jgJ14KGsh6uVm6jhz9aBTBcgx7iMuuP8zUbUE6nryHYXnR\ncSvuYSesTCoFfnL7elrZDak/n0jLfwUD80aWnReJfu9QQGdqdDnSG8lSQ1XPOC7O\n/hFW9l0TCzOE\n-----END CERTIFICATE-----", "aux": null, "e": "0x10001", "n": "0x25927b52ba5e68c8c9268bb9218f37673614ca65418f4745b143cd4ee53f9491c9a0e1c2f23a9516306affbf38667b871bc0cc82e60f5bb1a9fa15a5671a765c9f21b9587d80115964372a383c883b0dcbf6c775706b31eaff3e3fd488559a08cdea20f9a97c4c59b6b8a8eeca457d4a820d49509f759336302bca1a3690b08091811f858f2e8cea5a62355ad6e041d1935eda59289b597683b73e2657ae74bffc760e4d513cc87db9355918eaa08d398bbe5f6835dc87125211b9b36b3a0bc70b993a6cb3f7d2cb4061de73db972c942adf9955b6fe4cd90f00d088aec04af1f5eff91f21af5ed44617c7db8093f95366db26580c4af399deb94f9b141305be1", "marked": true, "time_years": 85.25100750352632, "price_aws_c4": 37365.516588795595}
> 2017-10-16 17:09:38 [32331] INFO ### SUMMARY ####################
> 2017-10-16 17:09:38 [32331] INFO Records tested: 1
> 2017-10-16 17:09:38 [32331] INFO .. PEM certs: . . . 1
> 2017-10-16 17:09:38 [32331] INFO .. DER certs: . . . 0
> 2017-10-16 17:09:38 [32331] INFO .. RSA key files: . 0
> 2017-10-16 17:09:38 [32331] INFO .. PGP master keys: 0
> 2017-10-16 17:09:38 [32331] INFO .. PGP total keys:  0
> 2017-10-16 17:09:38 [32331] INFO .. SSH keys:  . . . 0
> 2017-10-16 17:09:38 [32331] INFO .. APK keys:  . . . 0
> 2017-10-16 17:09:38 [32331] INFO .. JSON keys: . . . 0
> 2017-10-16 17:09:38 [32331] INFO .. LDIFF certs: . . 0
> 2017-10-16 17:09:38 [32331] INFO .. JKS certs: . . . 0
> 2017-10-16 17:09:38 [32331] INFO .. PKCS7: . . . . . 0
> 2017-10-16 17:09:38 [32331] INFO Fingerprinted keys found: 1
> 2017-10-16 17:09:38 [32331] INFO WARNING: Potential vulnerability
> 2017-10-16 17:09:38 [32331] INFO ################################

**Comment by unnawut** [comment]
It would be great if this is documented in the README. I'll submit a pull request ;)

**Comment by ph4r05** [comment]
Thanks for solving this. Closing.
